FROM eclipse-temurin:17
MAINTAINER sushantk297@gmail.com
COPY target/docker-product-server-0.0.1-SNAPSHOT.jar docker-product-server-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/docker-product-server-0.0.1-SNAPSHOT.jar"]